### ISSUE TITLE
Constructie voor mogelijk gedeeltelijk onbekende datum

### ISSUE THREAD

**Issue by fsamwel** [Geonovum/KP-APIs#18]
In sommige registraties is het mogelijk dat een datum slechts gedeeltelijk bekend is. Bijvoorbeeld wanneer we van een persoon alleen weten in welk jaar deze geboren is. Of dat alleen het jaar en de maand van de geboortedatum bekend is.

Overweging hierbij is dat:
- Dit soms voorkomt en een valide situatie is. Dit moet worden teruggeven in het antwoord.
- Het grootste deel van de datums wel volledig zijn. De oplossing moet het gebruik van de datum voor deze bulk van situaties niet (teveel) compliceren.

Wij (project voor API [bevragingen ingeschreven personen](https://github.com/VNG-Realisatie/Bevragingen-ingeschreven-personen)) zijn hier tot de conclusie gekomen dat dit op de volgende manier handig is om op te nemen.
Wanneer volledige datum bekend is:
```
"geboortedatum": {
      "datum": "1973-11-27",
      "jaar": "1973,
      "maand": "11",
      "dag": "27"
    }
```
Wanneer alleen jaar en maand bekend is:
```
"geboortedatum": {
      "jaar": "1973,
      "maand": "11"
    }
```

Ik wil voorstellen de api definitie hiervan ook op te nemen in [schemas.yaml](https://github.com/Geonovum/KP-API-guidelines/blob/master/components/schemas.yaml)
```
    Datum_onvolledig:
      type: "object"
      properties:
        datum:
          type: "string"
          title: "datum"
          format: "date"
          description: "De volledige datum die in de `date` definitie past. Dit element wordt alleen gevuld als de volledige datum bekend is."
        jaar:
          type: "string"
          title: "jaar"
          description: "Het jaar van de datum. Als het jaar bekend is wordt dit element gevuld, ook als de volledige datum bekend is."
          format: "date_fullyear"
          pattern: "^[1-2]{1}[0-9]{3}$"
        maand:
          type: "string"
          title: "maand"
          description: "De maand. Als de maand van een datum bekend is wordt dee hier ingeveuld. Ook als de volledige datum is ingevuld."
          format: "date_month"
          pattern: "^99$"
          maxLength: 2
        dag:
          type: "string"
          title: "dag"
          description: "De dag. Als de dag van de datum bekend is wordt deze hier ingevuld. Ook als de volledige datum bekend is."
          format: "date_mday"
          pattern: "^99$"
          maxLength: 2
```

N.B. besproken alternatieven:
1. Datum plus precisie
```
"geboortedatum": {
      "datum": "1973-01-01",
      "precisie": "jaar"
    }
```
Nadeel: de waarde van de datum kan een fictieve waarden hebben. Slordig gebruik van deze datum door consumer (niet raadplegen precisie) kan tot verkeerde interpretatie leiden.

2. Datum als oneOf date, jaar, jaarmaand
```
"geboortedatum": "datum": "1973-11-23"
"geboortedatum": "datum": "1973-11"
"geboortedatum": "datum": "1973"
```
Nadeel: datum kan niet direct gebruikt worden als date, waarmee gerekend kan worden. Consumer moet dit zelf afleiden.

3. Datum als lossen velden jaar, maand, dag
```
"geboortedatum": {
      "jaar": "1973,
      "maand": "11",
      "dag": "27"
    }
```
Nadeel: datum kan niet direct gebruikt worden als date, waarmee gerekend kan worden. Consumer moet dit zelf afleiden.
