### ISSUE TITLE
API-36 is te kort door de bocht gesteld

### ISSUE THREAD

**Issue by fsamwel** [Geonovum/KP-APIs#218]
> API-36: Provide a POST endpoint for GEO queries

Dit zegt dus dat het zoeken op een GEO gegeven altijd met een POST moet, ook wanneer het prima met een GET queryparameter had gekund. Als voorbeeld wordt in §12.2 het zoeken op een punt genoemd.

Dit kan prima in een queryparameter, bijvoorbeeld:
```
- in: query
  name: coordinates
  type: array
  explode: false
  example: '5.9623762,52.2118093'
  schema:
    type: array
    items:
      type: number
```

bijvoorbeeld zoeken van een pand op een geografisch punt kan dan met:
GET /panden?coordinates=5.9623762,52.2118093

Voordelen:
1. makkelijker in gebruik (voor client)
2. correct gebruik van HTTP methods (en daarmee RESTful)

Waarom zou dit verboden worden?
