### ISSUE TITLE
Wat is de maxLength van een URL in een OAS-specificatie?

### ISSUE THREAD

**Issue by HenriKorver** [Geonovum/KP-APIs#261]
Sommige API's eisen een maxLength voor de lengte van de URL. Hier een voorbeeld uit het OAS-schema van de Zaken API:

```yaml
properties:
        url:
          title: Url
          description: URL-referentie naar dit object. Dit is de unieke identificatie
            en locatie van dit object.
          type: string
          format: uri
          readOnly: true
          maxLength: 1000
          minLength: 1
```

**Eerste vraag:** is 1000 hier de juiste waarde voor maxLength?

Bijvoorbeeld, volgens stackoverflow is 2000 een betere bovengrens:
https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers

**Tweede vraag:** Wat is de meerwaarde om dit soort lengtebeperkingen mee te geven in een OAS-spec? 

In veel API's doen ze dat niet. Wellicht handig als de API Strategie hierover iets gaat zeggen.
